
logging:
    level:
        org.springframework.security: INFO
        root: INFO
    file: "application.log"

server:
    port: 8081

local:
    server:
        port: 8081


#jmx properties
jmx:
    config:
        username: "admin"
        password: "admin"


database:
    config:
        driver: "com.mysql.jdbc.Driver"
        url: "jdbc:mysql://localhost:3306/studentReportingSystem"
        username: "root"
        password: "Linux@121"
        initialSize: 10
        maxActive: 50
        maxWait: 1000

mybatis:
    executor-type: simple
